# SPDX-FileCopyrightText: 2025 The SonicWeb contributors.
# SPDX-License-Identifier: MPL-2.0

name: Compliance Checks

on: [push, pull_request]

jobs:
    REUSE:
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
              with:
                  egress-policy: audit

            - name: Checkout
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  fetch-depth: 1

            - name: REUSE Compliance Check
              uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 #v5.0.0
