# Copyright the SonicWeb contributors.
# SPDX-License-Identifier: MPL-2.0

name: Release

on:
    release:
        types:
            - published

permissions:
    contents: write

jobs:
    Build:
        strategy:
            matrix:
                go-version:
                    - stable
                architecture:
                    - 386
                    - amd64
                    - arm64
                os:
                    - linux
                    - windows
                    - darwin
                exclude:
                    - os: darwin
                      architecture: 386
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
              with:
                  egress-policy: audit

            - name: Install Go
              uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  fetch-depth: 1

            - name: Build
              env:
                  CGO_ENABLED: "0"
                  GOOS: ${{matrix.os}}
                  GOARCH: ${{matrix.architecture}}
              run: make

            - name: Compress
              run: xz -9 sonic-*-*

            - name: Upload Release
              uses: softprops/action-gh-release@v2
              with:
                  files: sonic-*-*.xz