# Copyright the SonicWeb contributors.
# SPDX-License-Identifier: MPL-2.0

name: Release

on:
    release:
        types:
            - published

permissions:
    contents: write

jobs:
    Build:
        strategy:
            matrix:
                go-version:
                    - stable
                architecture:
                    - "386"
                    - "amd64"
                    - "arm64"
                os:
                    - linux
                    - windows
                    - darwin
                exclude:
                    - os: darwin
                      architecture: 386
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with:
                  egress-policy: audit

            - name: Install Go
              uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Install nfpm
              if: matrix.os == 'linux'
              run: |
                  go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
                  echo "$(go env GOPATH)/bin" >> GITHUB_PATH

            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  fetch-depth: 1

            - name: Build
              env:
                CGO_ENABLED: "0"
                GOOS: ${{matrix.os}}
                GOARCH: ${{matrix.architecture}}
              run: make

            - name: Build Package
              if: matrix.os == 'linux'
              env:
                  CGO_ENABLED: "0"
                  GOOS: ${{matrix.os}}
                  GOARCH: ${{matrix.architecture}}
              run: make package

            - name: Compress
              run: xz -9 sonic-*-*

            - name: Upload Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      sonic-*-*.xz
                      SonicWeb*.rpm
                      SonicWeb*.deb