# Copyright the SonicWeb contributors.
# SPDX-License-Identifier: MPL-2.0

name: Release

on:
    release:
        types:
            - published

permissions:
    contents: write

jobs:
    Build:
        strategy:
            matrix:
                go-version:
                    - stable
                architecture:
                    - "386"
                    - "amd64"
                    - "arm64"
                os:
                    - linux
                    - windows
                    - darwin
                exclude:
                    - os: darwin
                      architecture: 386
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
              with:
                  egress-policy: audit

            - name: Install Go
              uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Install nfpm
              if: matrix.os == 'linux'
              run: |
                  go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
                  echo "$(go env GOPATH)/bin" >> GITHUB_PATH

            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  fetch-depth: 1

            - name: Build
              env:
                CGO_ENABLED: "0"
                GOOS: ${{matrix.os}}
                GOARCH: ${{matrix.architecture}}
              run: make

            - name: Build Package
              if: matrix.os == 'linux'
              env:
                  CGO_ENABLED: "0"
                  GOOS: ${{matrix.os}}
                  GOARCH: ${{matrix.architecture}}
              run: make package

            - name: Compress
              run: xz -9 sonic-*-*

            - name: Upload Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      sonic-*-*.xz
                      SonicWeb*.rpm
                      SonicWeb*.deb