# Copyright the SonicWeb contributors.
# SPDX-License-Identifier: MPL-2.0

name: Release

on:
    release:
        types:
            - published

permissions: read-all

jobs:
    Build:
        permissions:
            contents: write
        strategy:
            matrix:
                go-version:
                    - stable
                architecture:
                    - "386"
                    - "amd64"
                    - "arm64"
                os:
                    - linux
                    - windows
                    - darwin
                exclude:
                    - os: darwin
                      architecture: 386
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
              with:
                  egress-policy: audit

            - name: Install Go
              uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Install nfpm
              if: matrix.os == 'linux'
              run: |
                  go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
                  echo "$(go env GOPATH)/bin" >> GITHUB_PATH

            - name: Checkout
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  fetch-depth: 1

            - name: Build
              env:
                CGO_ENABLED: "0"
                GOOS: ${{matrix.os}}
                GOARCH: ${{matrix.architecture}}
              run: make

            - name: Build Package
              if: matrix.os == 'linux'
              env:
                  CGO_ENABLED: "0"
                  GOOS: ${{matrix.os}}
                  GOARCH: ${{matrix.architecture}}
              run: make package

            - name: Compress xz
              if: matrix.os != 'windows'
              run: xz -9 sonic-*-*

            - name: Compress 7z
              if: matrix.os == 'windows'
              uses: edgarrc/action-7z@93485892b5468e89cfb2c28a8d1c0e3904906458 # v1.0.5
              with:
                 args: 7z a -t7z -mx=9 sonic-${{matrix.os}}-${{matrix.architecture}}.7z sonic-${{matrix.os}}-${{matrix.architecture}}

            - name: Upload Release
              uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
              with:
                  files: |
                      sonic-*-*.7z
                      sonic-*-*.xz
                      SonicWeb*.rpm
                      SonicWeb*.deb