# Copyright the SonicWeb contributors.
# SPDX-License-Identifier: MPL-2.0

name: Release

on:
    release:
        types:
            - published

permissions:
    contents: write

jobs:
    Build:
        strategy:
            matrix:
                go-version:
                    - stable
                architecture:
                    - "386"
                    - "amd64"
                    - "arm64"
                os:
                    - linux
                    - windows
                    - darwin
                exclude:
                    - os: darwin
                      architecture: 386
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
              with:
                  egress-policy: audit

            - name: Install Go
              uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  fetch-depth: 1

            - name: Build
              env:
                  CGO_ENABLED: "0"
                  GOOS: ${{matrix.os}}
                  GOARCH: ${{matrix.architecture}}
              run: make package

            - name: Compress
              run: xz -9 sonic-*-*

            - name: Upload Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      sonic-*-*.xz
                      SonicWeb*.rpm
                      SonicWeb*.deb